#!/bin/bash
######################################################
#            PROJECT  : svUnitTest                   #
#            VERSION  : 0.5.0-dev                    #
#            DATE     : 11/2012                      #
#            AUTHOR   : Valat Sébastien              #
#            LICENSE  : CeCILL-C                     #
######################################################

######################################################
STATUS='run'

######################################################
if [ -z "$*" ]; then
	echo "Usage : svutserver {test_binary_1} [test_binary_2] ..." 1>&2
	exit 1
fi

######################################################
#create fifo file in tmp dir
dir=$(mktemp -p "/tmp" -d svutserver-XXXX) || { echo "Fail to create /tmp/svutserver-XXXX directory." 1>&2; exit 1; }
chmod go-wrx "$dir" || { echo "Fail to chmod $dir directory." 1>&2; rmdir "$dir"; exit 1; }
fifo="$dir/index.html"
mkfifo "$fifo" || { echo "Fail to create $fifo fifo." 1>&2; rmdir "$dir"; exit 1; }

######################################################
echo "============= svUnitTest server ==============="
echo ""
echo "Use this URL in your favorite brower and use F5"
echo "to re-run the tests :"
echo ""
echo "file://$fifo"
echo ""
echo "To stop the server, use CTRL+C"
echo ""
echo "==============================================="

######################################################
#cleanup on finish
function destroy_fifo_on_exit()
{
	echo "Halt and destroy temporary fifo."
	STATUS='halt'
	rm "$fifo" || exit 1
	rmdir "$dir" || exit 1
}

######################################################
#Setup halt handler
trap destroy_fifo_on_exit SIGINT

######################################################
echo "Test commands are : $*"
while [ "$STATUS" = 'run' ]; do
	svutxmlrun --html "$@" > "$fifo"
	echo "Work done."
done
